[build]
  command = "npm run build:static"  
  publish = "dist/static"           

[[redirects]]
  from = "/design/*"
  to = "https://design.spinlio.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/contact/*"
  to = "https://contact.spinlio.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200