[build]
  publish = "dist"           

[context.design]
  command = "npm run build:design"
  publish = "src/apps/design/dist"
  base = "/"

[context.marketplace]
  command = "npm run build:marketplace"
  publish = "src/apps/marketplace/dist"
  base = "/"

[[redirects]]
  from = "https://bazaar.it/*"
  to = "https://marketplace.bazaar.it/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.bazaar.it/*"
  to = "https://marketplace.bazaar.it/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200